### ISSUE TITLE
Issue parsing npm-install-checks

### ISSUE THREAD

**Issue by Kawacrepe** [NodeSecure/licenses-conformance#3]
There is an issue with npm-install-checks
![image](https://user-images.githubusercontent.com/40260517/142158865-2c00bf3a-b1b7-4754-b26c-c5a3985b2f94.png)

**Comment by fraxken** [comment]
It throw because some licenses are not OK.

- `BSD 3-Clause` instead of `BSD-3-Clause`
- `Apache` instead of `Apache-2.0`

I guess maybe we could solve part of the issue by using `spdx-license-ids` package. For Apache we replace by the right one and for other we could maybe fix issue by using a Levenshtein distance of 2 ?

So for example `BSD 3 Clause` would be the same as `BSD-3-Clause`
